name: momentica
description: "A new Flutter project."

publish_to: 'none'

# 주문 내역 페이지 퍼블리싱
version: 1.1.5+7

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.11
  go_router: ^14.3.0
  flutter_riverpod: ^2.6.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/image/core/momentica_app_image.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/diary/bookmark/
    - assets/diary/photo/
    - assets/diary/tick/
    - assets/icon/core/
    - assets/icon/auth/
    - assets/icon/my/
    - assets/icon/emotion/
    - assets/image/core/
    - assets/image/on_boarding/

  fonts:
    - family: WantedSans
      fonts:
        - asset: "assets/font/wanted_sans_semibold.otf"
          weight: 600
        - asset: "assets/font/wanted_sans_medium.otf"
          weight: 500
        - asset: "assets/font/wanted_sans_regular.otf"
          weight: 400
