name: momentica
description: "A new Flutter project."

publish_to: 'none'

# 메인 페이지 라우트 설정 및 코드 리팩토링
version: 1.1.2+4

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.11
  go_router: ^14.3.0
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icon/core/
    - assets/icon/auth/
    - assets/image/core/
    - assets/image/on_boarding/

  fonts:
    - family: WantedSans
      fonts:
        - asset: "assets/font/wanted_sans_semibold.otf"
          weight: 600
        - asset: "assets/font/wanted_sans_medium.otf"
          weight: 500
        - asset: "assets/font/wanted_sans_regular.otf"
          weight: 400
