name: momentica
description: "A new Flutter project."

publish_to: 'none'

# 1. 애플리케이션 번들 이름 + 아이콘 수정
# 2. 마이페이지 퍼블리싱
# 3. 마이페이지의 내 정보 및 수정 페이지 퍼블리싱
version: 1.1.3+5

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.11
  go_router: ^14.3.0
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/image/core/momentica_app_image.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/icon/core/
    - assets/icon/auth/
    - assets/icon/my/
    - assets/image/core/
    - assets/image/on_boarding/

  fonts:
    - family: WantedSans
      fonts:
        - asset: "assets/font/wanted_sans_semibold.otf"
          weight: 600
        - asset: "assets/font/wanted_sans_medium.otf"
          weight: 500
        - asset: "assets/font/wanted_sans_regular.otf"
          weight: 400
